# Generated by Django 3.2.6 on 2021-08-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='itme',
            new_name='item',
        ),
    ]
